enum ErrorCode {
  ValidationError = 'VALIDATION_ERROR',
  UserAlreadyExists = 'USER_ALREADY_EXISTS',
  WrongEmailOrPassword = 'WRONG_EMAIL_OR_PASSWORD',
  UserNotFound = 'USER_NOT_FOUND',
  InternalServerError = 'INTERNAL_SERVER_ERROR',
  FileIsRequired = 'FILE_IS_REQUIRED',
  Forbidden = 'FORBIDDEN',
  EmailNotSent = 'EMAIL_NOT_SENT',
  TemplateNotFound = 'TEMPLATE_NOT_FOUND',
  IncorrectRecoveryCode = 'INCORRECT_RECOVERY_CODE',
  EventNotFound = 'EVENT_NOT_FOUND',
  FileNotFound = 'FILE_NOT_FOUND',
  CategoryTranslationExists = 'CATEGORY_TRANSLATION_EXISTS',
  CategoryNotFound = 'CATEGORY_NOT_FOUND',
  PlaceNotFound = 'PLACE_NOT_FOUND',
  TicketVariantNotFound = 'TICKET_VARIANT_NOT_FOUND',
  CardNotFound = 'CARD_NOT_FOUND',
  InvalidFacebookAccessToken = 'INVALID_FACEBOOK_ACCESS_TOKEN',
  InvalidBooleanString = 'INVALID_BOOLEAN_STRING',
  EntityNotFound = 'ENTITY_NOT_FOUND',
  UserNotAuthenticated = 'USER_NOT_AUTHENTICATED',
  UsernameAlreadyExists = 'USERNAME_ALREADY_EXISTS',
  GenresNotFound = 'GENRES_NOT_FOUND',
}

export default ErrorCode
