services:
  postgres:
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    container_name: postgres
    ports:
      - ${DATABASE_PORT_OUTER}:${DATABASE_PORT_INNER}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql

  server:
    build:
      context: ..
      dockerfile: docker/server/Dockerfile
    container_name: server
    environment: 
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "/usr/local/bin/entrypoint.sh"]

volumes:
  db-data:
