services:
  postgres:
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    container_name: postgres
    ports:
      - ${DATABASE_PORT_OUTER}:${DATABASE_PORT_INNER}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql

  server:
    build:
      context: ..
      dockerfile: docker/server/Dockerfile
    container_name: server
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
      # opensearch-node1:
      #   condition: service_healthy
      # opensearch-node2:
      #   condition: service_healthy
      # migrations:
      #   condition: service_completed_successfully
    command: npm run start:prod

volumes:
  db-data:
